# Site settings
# in the templates available like {{ site.myvariable }}.
title: 笑一笑 没有什么大不了.
email: yaojohanan@gmail.com
brand: Yao Jia Hang
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: Jia Hang, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: yaojohanan@gmail.com
phone: 800-820-8820

# Tracking
googleAnalitycsID: UA-83933844-1

